### ISSUE TITLE
Length of input vector x ValueError

### ISSUE THREAD

**Issue by Fire39** [Italic-/ita_tools#1]
Hi,
First of all thanks for that script, it's awesome !

I found that if number of selected keys is <=20 then shows up error:
"# ValueError: The length of the input vector x must be at least padlen, which is 20."

Is that a limitation of using this method or can it be fixed?

PS: Would be awesome if MaxFreq could be filled in with typing exact number, because with a lot of data it's very laggy by using slider

**Comment by italic-r** [comment]
Should be fixed by 82517d701e07e1bcb3b6f46ddc8d99ea224856f3

Let me know if you still have issues. I was having problems a long while ago with padding, but I wasn't sure how I originally fixed it.

**Comment by Fire39** [comment]
Thanks, now it's working fine with less then 20 keyframes.

One more issue is that keyframes or curves have to be selected in graph editor.

"If no curves are selected, the filter will manipulate all visible curves in the graph editor."
It's not working for me

I'm using:
Maya 2018.4
numpy 1.9.2
scipy 0.16.0

**Comment by italic-r** [comment]
Woops! That was an oversight when adding the new feature. This should be fixed by 8d4e142b2818e2481a03d6b45ade81414ba571c3. Next task is to enable numerical input to the spinbox. Thanks for continuing to test!

**Comment by italic-r** [comment]
f3269d34218024c51d1ab0b29856a8d5a2c49fc2 Feature added, as requested. You can manually input numbers into the spinbox, plus you get the arrow buttons for incremental changes. This required some twiddling with Qt connections, which is likely far from ideal, but it works as I would expect. Since the original issue has been solved, I'm closing this issue. Feel free to open a new one for further bugs or requests.
